apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gym-frontend
  template:
    metadata:
      labels:
        app: gym-frontend
    spec:
      containers:
        - name: gym-frontend
          image: gym-frontend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: gym-frontend-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: gym-frontend
spec:
  selector:
    app: gym-frontend
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
