apiVersion: v1
kind: Service
metadata:
  name: gym-frontend
  namespace: default
spec:
  selector:
    app: gym-frontend
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30002
  type: NodePort
